#!/usr/bin/python

import sys
import cairo
from vcd.vcd import Vcd

WIDTH, HEIGHT = 600, 600

if len(sys.argv) != 2:
    print "Usage: %s FILE" % sys.argv[0]
    sys.exit(2)

steps = [(0, '0'), (30, 1), (40, 0), (60, 1)]

def process_steps(steps):
    result = []
    for i in range(len(steps)-1):
        value = steps[i][1]
        duration = steps[i+1][0] - steps[i][0]

        if i == 0:
            previous = None
        else:
            previous = steps[i-1][1]
        result.append((value, duration, previous))
    value = steps[-1][1]
    duration = 5
    previous = steps[-2][1]
    result.append((value, duration, previous))
    return result


def draw_steps(ctx, signal):
    now  = 0
    ctx.move_to(0,0)
    for value, duration, previous in process_steps(steps):
        if value not in (0, 1):
            value = 0
        ctx.line_to(now, -10*value)
        ctx.rel_line_to(duration, 0)
        now += duration
    ctx.stroke()

surface = cairo.ImageSurface (cairo.FORMAT_ARGB32, WIDTH, HEIGHT)
ctx = cairo.Context(surface)

ctx.set_source_rgb (1, 1, 1)
ctx.set_operator (cairo.OPERATOR_SOURCE)
ctx.paint()

v = Vcd(sys.argv[1])
ctx.set_source_rgb (0, 0, 1)
ctx.translate(0, 10)
ctx.save()
for signal in v.signals.values():
    ctx.set_font_size(11)
    ctx.new_path()
    ctx.text_path(signal.reference)
    ctx.fill()
    ctx.translate(0, 20)

ctx.restore()
for signal in v.signals.values():
    ctx.save()
    ctx.translate(100, 0)
    draw_steps(ctx, signal)
    ctx.restore()
    ctx.translate(0, 20)

surface.write_to_png('vcd.png')
