#!/usr/bin/python

import sys
import cairo
from vcd.vcd import Vcd

WIDTH, HEIGHT = 600, 600

if len(sys.argv) != 3:
    print "Usage: %s INPUT OUTPUT" % sys.argv[0]
    sys.exit(2)

input = sys.argv[1]
output = sys.argv[2]

text_color           = (0, 0, 0)
default_fill_color   = (0.8, 1, 0.8)
default_stroke_color = (0.5, 1, 0.5)
unknown_fill_color   = (1, 0.8, 0.8)
unknown_stroke_color = (1, 0.5, 0.5)

def process_steps(steps, total):
    result = []
    for i in range(len(steps)-1):
        value = steps[i][1]
        duration = int(steps[i+1][0]) - int(steps[i][0])
        duration /= 100000
        result.append((value, duration))

    value = steps[-1][1]
    duration = total - int(steps[-1][0])
    duration /= 100000
    result.append((value, duration))
    return result


def draw_steps_single(ctx, signal, total):
    now  = 0
    ctx.move_to(0,0)
    for value, duration in process_steps(signal.steps, total):
        if value in ('0', '1'):
            ctx.set_source_rgb (*default_stroke_color)
            ctx.line_to(now, -10*int(value))
            ctx.rel_line_to(duration, 0)
        else:
            ctx.stroke()
            ctx.set_source_rgb (*unknown_fill_color)
            x, y = ctx.get_current_point()
            ctx.rectangle(x, 0, duration, -10)
            ctx.fill()
            ctx.set_source_rgb (*unknown_stroke_color)
            ctx.move_to(x, -10)
            ctx.rel_line_to(duration, 0)
            ctx.move_to(x, 0)
            ctx.rel_line_to(duration, 0)
            ctx.stroke()
        now += duration
    ctx.stroke()

def draw_steps_register(ctx, signal, total):
    offset = 2.5
    heigth = 10
    ctx.move_to(0, -heigth/2)
    steps = process_steps(signal.steps, total)
    for value, duration in steps[:-1]:
        x, y = ctx.get_current_point()
        ctx.line_to(x+offset, -heigth)
        ctx.line_to(x+duration-offset, -heigth)
        ctx.line_to(x+duration, -heigth/2)
        ctx.line_to(x+duration-offset, 0)
        ctx.line_to(x+offset, 0)
        ctx.close_path()
        if 'U' in value:
            ctx.set_source_rgb (*unknown_fill_color)
            ctx.fill_preserve()
            ctx.set_source_rgb (*unknown_stroke_color)
            ctx.stroke()
        else:
            ctx.set_source_rgb (*default_fill_color)
            ctx.fill_preserve()
            ctx.set_source_rgb (*default_stroke_color)
            ctx.stroke()
        ctx.move_to(x+duration, -heigth/2)
    value, duration = steps[-1]
    x, y = ctx.get_current_point()
    ctx.move_to(x+duration, 0)
    ctx.line_to(x+offset, 0)
    ctx.line_to(x, -heigth/2)
    ctx.line_to(x+offset, -heigth)
    ctx.line_to(x+duration, -heigth)
    if 'U' in value:
        ctx.set_source_rgb (*unknown_fill_color)
        ctx.fill_preserve()
        ctx.set_source_rgb (*unknown_stroke_color)
        ctx.stroke()
    else:
        ctx.set_source_rgb (*default_fill_color)
        ctx.fill_preserve()
        ctx.set_source_rgb (*default_stroke_color)
        ctx.stroke()


surface = cairo.ImageSurface (cairo.FORMAT_ARGB32, WIDTH, HEIGHT)
ctx = cairo.Context(surface)

ctx.set_source_rgb (1, 1, 1)
ctx.set_operator (cairo.OPERATOR_SOURCE)
ctx.paint()

v = Vcd(input)
ctx.set_source_rgb (*text_color)
ctx.translate(0, 10)
ctx.save()
for signal in v.signals.values():
    ctx.set_font_size(11)
    ctx.new_path()
    ctx.text_path(signal.reference)
    ctx.fill()
    ctx.translate(0, 20)

ctx.restore()

total = 0
for signal in v.signals.values():
    total = max([total] + [int(s[0]) for s in signal.steps])

for signal in v.signals.values():
    ctx.save()
    ctx.translate(100, 0)
    if signal.size == 1:
        draw_steps_single(ctx, signal, total)
    else:
        draw_steps_register(ctx, signal, total)
    ctx.restore()
    ctx.translate(0, 20)

surface.write_to_png(output)
